# Generated by Django 5.1.8 on 2025-05-26 17:40

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('beds_count', models.IntegerField()),
                ('baths_count', models.IntegerField()),
                ('area', models.IntegerField()),
                ('price', models.FloatField()),
                ('image', models.ImageField(upload_to='img')),
                ('description', models.TextField(max_length=500)),
                ('slug', models.SlugField()),
            ],
            options={
                'db_table': 'property_offers',
            },
        ),
    ]
